spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    host: jdbc:mysql://localhost:3306
    username: root
    password: admin
    url: jdbc:mysql://localhost/ilhapet?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
