insert into role(authority) values (0);
insert into role(authority) values (1);

insert into user(name, password, email, username, telefone, enabled, access_level_id) values ('admin', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'admin_user@mail.com', 'admin_user@mail.com', "98982734057", true, 2),('user', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 'user_user@mail.com', 'user_user@mail.com', "98982734057", true, 1);

insert into vacina(name, doses, tipo) values ('Múltipla (Virose) - Canino', 4, 0);
insert into vacina(name, doses, tipo) values ('Múltipla (Virose) - Felino', 4, 1);
insert into vacina(name, doses, tipo) values ('Antirrábica - Canino', 1, 0);
insert into vacina(name, doses, tipo) values ('Antirrábica - Felino', 1, 1);
insert into vacina(name, doses, tipo) values ('Gripe Canina', 1, 0);
insert into vacina(name, doses, tipo) values ('Bronchguard', 2, 0);
insert into vacina(name, doses, tipo) values ('Giardia', 2, 0);
insert into vacina(name, doses, tipo) values ('Leishmaniose', 3, 0);
insert into vacina(name, doses, tipo) values ('Dirofilariose (Verme do coração)', 1, 0);

insert into exame(name) values ('Hemograma');
insert into exame(name) values ('Contagem de reticulócito a');
insert into exame(name) values ('ALT');
insert into exame(name) values ('AST');
insert into exame(name) values ('Fosfatase Alcalina');
insert into exame(name) values ('Creatinina');
insert into exame(name) values ('Ureia');
insert into exame(name) values ('Proteína total e fração');
insert into exame(name) values ('4DX');
insert into exame(name) values ('Perfil 6');
insert into exame(name) values ('Perfil 10');
insert into exame(name) values ('Perfil 4');
insert into exame(name) values ('SDMA');
insert into exame(name) values ('Pesquisa de babesia');
insert into exame(name) values ('Pesquisa de erlichia');
insert into exame(name) values ('Pesquisa de mycoplasma');
insert into exame(name) values ('Elisa e Rifi diluição total');
insert into exame(name) values ('Alere Parvovirose Ag');
insert into exame(name) values ('Alere Cinomose Ag');
insert into exame(name) values ('Alere Fiv/felv');
insert into exame(name) values ('Alere Dirofilariose');
insert into exame(name) values ('Alere leishmaniose Ac');
insert into exame(name) values ('Parasitológico de fezes');
insert into exame(name) values ('Parasitológico de fezes seriado');
insert into exame(name) values ('Citologia de pele');
insert into exame(name) values ('Microscopia de pele');
insert into exame(name) values ('Citologia de 1 ouvido');
insert into exame(name) values ('Citologia de 2 ouvidos');
insert into exame(name) values ('Citopatologico');
insert into exame(name) values ('Urinalise');
insert into exame(name) values ('Eletrocardiograma');
insert into exame(name) values ('Ultrassom');
insert into exame(name) values ('Raio - x');

--insert into veterinario(name) values('Anny Hellen Santos - Clínico geral');
--insert into veterinario(name) values('Gleice Caroline - Clínico geral');
--insert into veterinario(name) values('Samilia Alves - Clínico geral');
--insert into veterinario(name) values('Rayane Diniz - Clínico geral');
--insert into veterinario(name) values('Roberta Castro - Clínico geral');
--insert into veterinario(name) values('Beatriz Rocha   - Clínico geral');
--insert into veterinario(name) values('Larissa Moraes - Clínico geral');
--insert into veterinario(name) values('Thamiza Santos - Dermatologista');
--insert into veterinario(name) values('Rayssa Vaz - Odontologista');
--insert into veterinario(name) values('Osnnyr Cutrim - Ortopedista');
--insert into veterinario(name) values('Sabrina Bastos - Endocrinologia');
--insert into veterinario(name) values('Nathália Sarges - Oftalmologista');
--insert into veterinario(name) values('Dayse Lima - Neurologista');
--insert into veterinario(name) values('Alessandra Rocha - Oncologista');
--insert into veterinario(name) values('Leela Costa - Nutricionista');
--insert into veterinario(name) values('Dglan Dourado - Cardiologista');
--insert into veterinario(name) values('Hallef Trovão - Gastroenterologista');